name: mvas
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - appdirs=1.4.4
  - blas=1.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0 
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - cloudpickle=2.0.0
  - cryptography=39.0.1
  - cudatoolkit=11.3.1
  - cytoolz=0.12.0
  - dask-core=2022.7.0
  - embree=4.0.1
  - ffmpeg=4.3
  - flit-core=3.6.0
  - freetype=2.12.1
  - fsspec=2022.11.0
  - giflib=5.2.1
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.26.0
  - intel-openmp=2021.4.0
  - jpeg=9e
  - jxrlib=1.1
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.87.0
  - libdeflate=1.17
  - libffi=3.4.2
  - libhwloc=2.9.0
  - libiconv=1.16
  - libpng=1.6.39
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - networkx=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - partd=1.2.0
  - pillow=9.4.0
  - pip=23.0.1
  - pooch=1.4.0
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.9.16
  - python_abi=3.9
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pywavelets=1.4.1
  - pyyaml=6.0
  - requests=2.28.1
  - scikit-image=0.19.3
  - setuptools=65.6.3
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.40.1
  - tbb=2021.8.0
  - tifffile=2021.7.2
  - tk=8.6.12
  - toolz=0.12.0
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - trimesh=3.20.2
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.2.10
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - addict==2.4.0
    - asttokens==2.2.1
    - attrs==22.2.0
    - backcall==0.2.0
    - click==8.1.3
    - comm==0.1.2
    - configargparse==1.5.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - dash==2.8.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.6.6
    - decorator==5.1.1
    - executing==1.2.0
    - fastjsonschema==2.16.3
    - flask==2.2.3
    - fonttools==4.39.0
    - importlib-metadata==6.0.0
    - importlib-resources==5.12.0
    - ipykernel==6.21.3
    - ipython==8.11.0
    - ipywidgets==8.0.4
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - jupyter-client==8.0.3
    - jupyter-core==5.2.0
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.4
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - nbformat==5.5.0
    - nest-asyncio==1.5.6
    - open3d==0.16.0
    - opencv-python==4.7.0.72
    - packaging==23.0
    - pandas==1.5.3
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==3.1.0
    - plotly==5.13.1
    - prompt-toolkit==3.0.38
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pygments==2.14.0
    - pyhocon==0.3.59
    - pymcubes==0.1.4
    - pyparsing==2.4.7
    - pyquaternion==0.9.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - pyzmq==25.0.0
    - scikit-learn==1.2.1
    - scipy==1.10.1
    - stack-data==0.6.2
    - tenacity==8.2.2
    - threadpoolctl==3.1.0
    - tornado==6.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - wcwidth==0.2.6
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.5
    - zipp==3.15.0
